### ISSUE TITLE
BrandBand background images 404 in production use

### ISSUE THREAD

**Issue by extronics** [propertybase/react-lds#302]
The background image urls come straight from the CSS and therefore ignore the `sldsAssetRoot` setting. When using the react-lds as a static resource in SF, the background images 404 because of this.

**Comment by fspoettel** [comment]
Not a bug on our side, this needs to be fixed upstream

**Comment by fspoettel** [comment]
Tracking in https://github.com/salesforce-ux/design-system/issues/539

**Comment by fspoettel** [comment]
Will be fixed with move to `<apex:slds />` for us, so this problem will only affect our docs for now.
