### ISSUE TITLE
"stretch" is not a button flavor

### ISSUE THREAD

**Issue by philippfrank** [propertybase/react-lds#418]
See: https://www.lightningdesignsystem.com/components/buttons/#Sizing

It should be applicable in addition to - for example - a `brand` flavor, maybe using a `stretch` prop.

**Comment by fspoettel** [comment]
Flavors are not mutually exclusive. They share the fact that they map to `_flavor` classes

You can always set `flavor={['stretch', 'brand']}`

**Comment by philippfrank** [comment]
Not in this case as I understand, it uses `oneOf`: https://github.com/propertybase/react-lds/blob/master/src/components/Button/Base/Button.js#L97

**Comment by philippfrank** [comment]
I will open a PR for this.
