### ISSUE TITLE
Rework DataTable

### ISSUE THREAD

**Issue by fspoettel** [propertybase/react-lds#55]
The DataTable-Component in its current form is not consistent with the rest of the repository after we added behavior to other components. Resizing and sorting is currently implemented via HoC on the individual Cells and I'm not sure whether this is enough to actually add this functionality to the component. These HoC are also not documented in the `Cell`-PropTypes which makes them pretty cryptic. At the very least, we should try to implement the functionality and either add it to the component itself or provide additional hooks to make it seamless.

**Comment by extronics** [comment]
Closed by #97
